### ISSUE TITLE
Unicode symbols in strings are broken

### ISSUE THREAD

**Issue by kanaka** [kanaka/clojurescript#10]
ClojureScript (with _debug_ enabled):

```
cljs.user=> "ü"
READ: "ü"
ANALYZED: "ü"
EMITTED: "\"\\u%04X\""
ERR: SyntaxError: Unexpected token ILLEGAL
...
```

Clojure:

```
user=> "ü"
"ü"
```

**Comment by Gozala** [comment]
Looks like issue comes from the format function:

Clojure:

``` clojure
(format "\\u%04X" 252)
"\\u00FC"
```

ClojureScript

``` clojure
(format "\\u%04X" 252)
"\\u%04X"
```

I'll try to dig into this, although I'm not familiar with format function :(

**Comment by Gozala** [comment]
Ok it looks like cljs format uses google clojuse [stringformat](http://closure-library.googlecode.com/svn/docs/closure_goog_string_stringformat.js.html) that implements python like formatting instead of Java like one,
which I guess is a cause of the issue.
