### ISSUE TITLE
UI (jquery.console) annoyances (long lines, copy/paste)

### ISSUE THREAD

**Issue by kanaka** [kanaka/clojurescript#15]
The new UI from the Himera site uses jquery.console for the interactive part (and history). It looks nice but has some usage annoyances:

```
* long-lines can cause the cursor to disappear until you hit enter
* selecting text will immediately unselect making copy difficult
* using middle click (in X) to paste doesn't work (Ctrl-V paste does work)
```

**Comment by kanaka** [comment]
Looks like https://github.com/replit/jq-console might make a pretty easy replacement for jquery-console (similar API).

**Comment by Gozala** [comment]
If that's interesting I could probably make version of [interactivate](http://jeditoolkit.com/interactivate/) for cljs.

**Comment by kanaka** [comment]
@Gozala yeah, there are probably several different modes that are desirable and an interactivate style "REPL" would certainly be a great idea. A more traditional REPL (where you just edit one line at a time at the bottom) will probably appeal more to Clojure people (at first) who come from that mode of operation.

I'm also envisioning a mode of building ClojureScript projects that would build the project with the cljs-in-cljs builtin and provide a debug window popup (programmatically and/or via a floating button perhaps) that would basically be a ClojureScript REPL that would allow inspection and debug of the live running ClojureScript app. Think firebug but for ClojureScript rather than Javascript. In that context, I think a vprint functions that renders a given datastructure/object like interactivate does would be quite useful. Just some random thoughts.

I noticed the interactive uses CodeMirror. I've only briefly used ACE before, but I do see a bunch of places where CodeMirror and ACE are compared. Do you have a preference of one over the other? Reasons? Mostly I'm just curious since I'm not intimately familiar with either of them.

**Comment by Gozala** [comment]
> I noticed the interactive uses CodeMirror. I've only briefly used ACE before, but I do see a bunch of places where CodeMirror and ACE are compared. Do you have a preference of one over the other? Reasons? Mostly I'm just curious since I'm not intimately familiar with either of them.

I've being using ACE in the past for most of the editor related projects, but it was hell to maintain and keep in sync
also bunch of my contributions are still pending I think. With codemirror I find it to be a lot more easier to embed and
maintain and there are almost no breaking changes. I do believe that ACE got better now, but I still prefer codemirror
as it requires less tooling & work. I think ACE has more features though. For interactivate specifically I also use codemirrors inline widgets that can be deleted as chars etc.. I don't believe ACE has anything similar.

In the nutshell ACE purpose is to be an editor component for cloud 9, while codemirror whole purpose is to embeddable code editing component for web. I think that's observable both in architecture and the way
 projects are run.

**Comment by Gozala** [comment]
> @Gozala yeah, there are probably several different modes that are desirable and an interactivate style "REPL" would certainly be a great idea. A more traditional REPL (where you just edit one line at a time at the bottom) will probably appeal more to Clojure people (at first) who come from that mode of operation.

I do like REPLs but it requires repetition and multiline code is often a pain too, this pushed me towards something like interactivate. But yes I do get your point.

> I'm also envisioning a mode of building ClojureScript projects that would build the project with the cljs-in-cljs builtin and provide a debug window popup (programmatically and/or via a floating button perhaps) that would basically be a ClojureScript REPL that would allow inspection and debug of the live running ClojureScript app. Think firebug but for ClojureScript rather than Javascript. In that context, I think a vprint functions that renders a given datastructure/object like interactivate does would be quite useful. Just some random thoughts.

My long temp goal with interactivate is to power a code examples in docs. Imagine if you could just tweak examples in clojuredocs.org and see the output. With JS is a lot harder though, doing something like that with cljs-in-cljs would
be a lot simpler and hopefully we'll have that at some point.

As of output it prints it's not quite what I want yet I do use polymorphic [methods](https://github.com/Gozala/method)
inspired by clojure protocols to customize output. In a future I plan to have output for langauge constructs similar to
one you see in webinspector that lets you expand props etc.. For DOM it will be still element but maybe with a HTML panel next to it similar to webinpectors HTML panel. For debug I usually just put `debugger` statement which triggers
webinpector and open up debugger. With source maps that will work for fine for cljs too ;)

**Comment by kanaka** [comment]
@arthuredelstein, the new REPL with jq-console is much improved. However, some of the original issues with jquery-console are still there. Long lines are still problematic. Perhaps automatic wrapping or scrolling would help. Also, if you are at the end of a long line and press enter it should scroll back to the left automatically.

Middle click paste doesn't work here either. You can now select text and middle paste to another window, but you can't select and then middle paste into the console itself.

**Comment by amasad** [comment]
not to hijack the thread like this but @arthuredelstein mentioned clojurescript repl on a jqconsole issue. Congrats on self-hosting.
We used to do auto scroll on repl.it & jqconsole but we noticed word-wrap is much nicer, you can add word wrap by applying the following to jqconsole:

``` css
.jqconsole {
  white-space: pre-wrap;
  word-wrap: break-word;
}
```

For the middle key, AFAIK browsers do not emit the paste event in browsers so we don't have access to the clipboard (last checked on firefox on ubuntu). does it work on codemirror or ace? if so I can probably get it to work on jqconsole.

**Comment by kanaka** [comment]
@amasad, no problem. This issue is for discussing exactly that type of thing.

Thanks for the suggestion. That makes long-line handling much better.

I tried several CodeMirror demos and they all seem to support middle-click paste. I was going to try in repl.it too, but I am unable to load repl.it at the moment. I get the following Javascript error:

```
Uncaught TypeError: Cannot read property 'FoldMode' of null 
```

**Comment by amasad** [comment]
What browser/os are using?

**Comment by kanaka** [comment]
Chrome 23, Ubuntu Maverick. Seems to be working now though after switch to languages and back again.

Now that it's working I can confirm that middle-click paste works in the left edit pane but not on the right side console.

**Comment by amasad** [comment]
ok thanks. will look into that.

**Comment by kanaka** [comment]
Closing since after merging @amasad's pull request https://github.com/kanaka/clojurescript/pull/24 middle-click paste now works.

**Comment by arthuredelstein** [comment]
Great!

On Wednesday, February 13, 2013, Joel Martin wrote:

> Closing since after merging @amasad https://github.com/amasad's pull
> request #24 https://github.com/kanaka/clojurescript/issues/24middle-click paste now works.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/kanaka/clojurescript/issues/15#issuecomment-13523680.

## 

Arthur
